### ISSUE TITLE
Make DocumentCollection thread safe

### ISSUE THREAD

**Issue by ttu** [ttu/json-flatfile-datastore#4]
Use lock when accessing DocumentCollection's internal list

```csharp
[Fact]
public async Task InsertOne_1000ParallelAsync()
{
	var newFilePath = UTHelpers.Up();

	var store = new DataStore(newFilePath);

	var collection = store.GetCollection<User>("user");
	Assert.Equal(3, collection.Count);

	var tasks = Enumerable.Range(0, 1000)
		.AsParallel()
		.Select(i => collection.InsertOneAsync(new User { Id = i, Name = "Teddy" }))
		.ToList();

	await Task.WhenAll(tasks);

	var store2 = new DataStore(newFilePath);
	var collection2 = store2.GetCollection<User>("user");
	Assert.Equal(1003, collection2.Count);
	var distinct = collection2.AsQueryable().GroupBy(e => e.Id).Select(g => g.First());
	Assert.Equal(1003, distinct.Count());

	UTHelpers.Down(newFilePath);
}
```

```
Result StackTrace:	
at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at JsonFlatFileDataStore.DocumentCollection`1.GetNextIdValue(List`1 data) in C:\src\GitHub\json-flatfile-datastore\JsonFlatFileDataStore\DocumentCollection.cs:line 364
   at JsonFlatFileDataStore.DocumentCollection`1.<>c__DisplayClass14_0.<InsertOneAsync>b__0(List`1 data) in C:\src\GitHub\json-flatfile-datastore\JsonFlatFileDataStore\DocumentCollection.cs:line 58
   at JsonFlatFileDataStore.DocumentCollection`1.<InsertOneAsync>d__14.MoveNext() in C:\src\GitHub\json-flatfile-datastore\JsonFlatFileDataStore\DocumentCollection.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at JsonFlatFileDataStore.Test.CollectionTests.<InsertOne_100Async>d__26.MoveNext() in C:\src\GitHub\json-flatfile-datastore\JsonFlatFileDataStore.Test\CollectionTests.cs:line 771
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
```

**Comment by ttu** [comment]
Fixed in https://github.com/ttu/json-flatfile-datastore/commit/da7a894f691e90e1cb2cf8a9223d3f9344dde113
